# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a322f0056d53da4de1c3506867a2f3d50a19a7e4b71108b1852d22a305ea82441076860da3a3727919bb3184b0dfde3574a95f916a995404a805d8ed806af5c5

test:
  secret_key_base: 45873a3f8896d633346a308f005dd4a95425f84e6205412a0fb82aed6b79e564e45994bdab98b7e62275ae4b24fb375dfaccaf7326291367e172db4a282a8d2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
